{{- if .Values.prometheus.slos.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "quarkus-app.fullname" . }}-slos
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    role: alert-rules
    app: prometheus
spec:
  groups:
  - name: {{ include "quarkus-app.fullname" . }}.slos.rules
    rules:
    # Availability: Ensures that the application has an uptime of 99.9% over a 10-minute window.
    - alert: {{ include "quarkus-app.fullname" . }} Availability Below Threshold
      annotations:
        message: '{{ include "quarkus-app.fullname" . }} in namespace {{ .Values.namespace }} has been unavailable for more than 0.1% in the last 10 minutes.'
      expr: (1 - avg_over_time(up{namespace="{{ .Values.namespace }}", app="{{ include "quarkus-app.fullname" . }}"}[10m])) > 0.001
      for: 1m
      labels:
        severity: {{ .Values.prometheus.slos.severity | default "warning" }}

    # API Response Time: Average response time for API requests should be under 200ms.
    - alert: {{ include "quarkus-app.fullname" . }} High API Response Time
      annotations:
        message: '{{ include "quarkus-app.fullname" . }} in namespace {{ .Values.namespace }} has an average response time of more than 200ms in the last 10 minutes.'
      expr: rate(http_request_duration_seconds_sum{namespace="{{ .Values.namespace }}", app="{{ include "quarkus-app.fullname" . }}"}[10m]) / rate(http_request_duration_seconds_count{namespace="{{ .Values.namespace }}", app="{{ include "quarkus-app.fullname" . }}"}[10m]) > 0.2
      for: 10m
      labels:
        severity: {{ .Values.prometheus.slos.severity | default "warning" }}

    # Error Rate: Less than 0.1% of all API requests should result in errors (4xx and 5xx responses).
    - alert: {{ include "quarkus-app.fullname" . }} High Error Rate
      annotations:
        message: '{{ include "quarkus-app.fullname" . }} in namespace {{ .Values.namespace }} has an error rate of more than 0.1% in the last 10 minutes.'
      expr: rate(http_requests_total{namespace="{{ .Values.namespace }}", app="{{ include "quarkus-app.fullname" . }}", status=~"4..|5.."}[10m]) / rate(http_requests_total{namespace="{{ .Values.namespace }}", app="{{ include "quarkus-app.fullname" . }}"}[10m]) > 0.001
      for: 10m
      labels:
        severity: {{ .Values.prometheus.slos.severity | default "warning" }}
    
    # Elevator Response Time: Ensure elevators respond and arrive within 30 seconds of a request during fire incidents.
    - alert: {{ include "quarkus-app.fullname" . }} Elevator Response Time Exceeded
      annotations:
        message: '{{ include "quarkus-app.fullname" . }} in namespace {{ .Values.namespace }} has an average elevator response time of more than 30 seconds in the last 10 minutes.'
      expr: rate(camel_route_policy_seconds{namespace="{{ .Values.namespace }}", app="{{ include "quarkus-app.fullname" . }}", route="ElevatorProcessing"}[10m]) > 30
      for: 10m
      labels:
        severity: {{ .Values.prometheus.slos.severity | default "warning" }}

    # Stairs Traffic Flow: Ensure a steady flow of individuals using stairs, avoiding bottlenecks or overcrowding.
    - alert: {{ include "quarkus-app.fullname" . }} Stairs Traffic Congestion
      annotations:
        message: '{{ include "quarkus-app.fullname" . }} in namespace {{ .Values.namespace }} shows congestion or potential overcrowding in stairwells in the last 10 minutes.'
      expr: rate(camel_exchanges_inflight{namespace="{{ .Values.namespace }}", app="{{ include "quarkus-app.fullname" . }}", route="StairsProcessing"}[10m]) > 5
      for: 10m
      labels:
        severity: {{ .Values.prometheus.slos.severity | default "warning" }}

    # High External Redeliveries: Alert for high external redeliveries.
    - alert: {{ include "quarkus-app.fullname" . }} High External Redeliveries
      annotations:
        message: '{{ include "quarkus-app.fullname" . }} in namespace {{ .Values.namespace }} has more than 3 external redeliveries in the last 10 minutes.'
      expr: rate(camel_exchanges_external_redeliveries_total{namespace="{{ .Values.namespace }}", app="{{ include "quarkus-app.fullname" . }}"}[10m]) > 3
      for: 10m
      labels:
        severity: {{ .Values.prometheus.slos.severity | default "warning" }}
{{ end }}
