{{- if .Values.prometheus.elevator.slos.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "quarkus-app.fullname" . }}-elevator-stairs-slos
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    role: alert-rules
    app: prometheus
spec:
  groups:
  - name: {{ include "quarkus-app.fullname" . }}.slos.rules
    rules:
    # Elevator Response Time Rule during Fire Incidents:
    # This rule alerts when the average elevator response time exceeds 30 seconds within a 10-minute window during fire incidents.
    - alert: {{ include "quarkus-app.fullname" . }} Elevator Response Time Exceeded
      annotations:
        message: '{{ include "quarkus-app.fullname" . }} in namespace {{ .Values.namespace }} has an average elevator response time of more than 30 seconds in the last 10 minutes.'
      expr: rate(camel_route_policy_seconds{namespace="{{ .Values.namespace }}", app="{{ include "quarkus-app.fullname" . }}", route="ElevatorProcessing"}[10m]) > 30
      for: 10m
      labels:
        severity: {{ .Values.prometheus.elevator.slos.severity | default "warning" }}

    # Stairs Traffic Flow Rule:
    # This rule alerts when there's a potential congestion or overcrowding in stairwells within a 10-minute window.
    - alert: {{ include "quarkus-app.fullname" . }} Stairs Traffic Congestion
      annotations:
        message: '{{ include "quarkus-app.fullname" . }} in namespace {{ .Values.namespace }} shows congestion or potential overcrowding in stairwells in the last 10 minutes.'
      expr: rate(camel_exchanges_inflight{namespace="{{ .Values.namespace }}", app="{{ include "quarkus-app.fullname" . }}", route="StairsProcessing"}[10m]) > 5
      for: 10m
      labels:
        severity: {{ .Values.prometheus.elevator.slos.severity | default "warning" }}

    # High External Redeliveries Rule:
    # This rule alerts when the total number of external redeliveries exceeds 3 within a 10-minute window.
    - alert: {{ include "quarkus-app.fullname" . }} High External Redeliveries
      annotations:
        message: '{{ include "quarkus-app.fullname" . }} in namespace {{ .Values.namespace }} has more than 3 external redeliveries in the last 10 minutes.'
      expr: rate(camel_exchanges_external_redeliveries_total{namespace="{{ .Values.namespace }}", app="{{ include "quarkus-app.fullname" . }}"}[10m]) > 3
      for: 10m
      labels:
        severity: {{ .Values.prometheus.elevator.slos.severity | default "warning" }}
    
    # Latency SLO Breach for Elevator Rule:
    # This rule is designed to monitor the elevator response time and ensure it adheres to the defined Service Level Objective (SLO) of 99.9%.
    # Specifically, it checks if over 99.9% of the elevator response times are below 0.05 seconds within a 5-minute window.
    # If the percentage of response times below 0.05 seconds drops below 99.9%, an alert is triggered indicating a breach of the latency SLO.
    - alert: {{ include "quarkus-app.fullname" . }} Elevator Response Time Breach
      annotations:
        message: '{{ include "quarkus-app.fullname" . }} in namespace {{ .Values.namespace }} has an average elevator response time greater than 0.05 seconds in the last 5 minutes.'
      expr: (count_over_time((elevatorTimerRequest_seconds_max{camelContext="camel-1", container="mobility-app"} < 0.05 )[5m:]) / count_over_time((elevatorTimerRequest_seconds_max{camelContext="camel-1", container="mobility-app"})[5m:])) * 100 < 99.9
      for: 5m
      labels:
        severity: {{ .Values.prometheus.elevator.slos.severity | default "critical" }}

    # Availability SLO Breach Rule:
    # This rule monitors the availability of the service, aiming to uphold the defined Service Level Objective (SLO) of 99.9%.
    # It calculates the percentage of successful exchanges over total exchanges within a 5-minute window.
    # If the percentage of successful exchanges drops below 99.9%, an alert is triggered indicating a breach of the availability SLO.
    - alert: {{ include "quarkus-app.fullname" . }} Availability Breach
      annotations:
        message: '{{ include "quarkus-app.fullname" . }} in namespace {{ .Values.namespace }} has an availability lower than 99.9% in the last 10 minutes.'
      expr: (sum(delta(camel_exchanges_succeeded_total{container="mobility-app", routeId="ElevatorProcessing"}[5m])) / sum(delta(camel_exchanges_total{container="mobility-app", routeId="ElevatorProcessing"}[5m]))) * 100 < 99.9
      for: 5m
      labels:
        severity: {{ .Values.prometheus.elevator.slos.severity | default "critical" }}

{{ end }}
